language: node_js
node_js: stable
branches:
  only:
  - master
before_install:
- npm install -g vuepress
install:
- npm install
script:
- npm run build
after_success:
- cd .vuepress/dist
- git init
- git config --global user.name 'heimanba'
- git config --global user.email '783962369@qq.com'
- git add .
- git commit -m "generate static resources, triggerd by travis ci"
- git push -f "https://${REPO_TOKEN}@${GH_REF}" master:gh-pages
env:
  global:
  - GH_REF: github.com/Uheinanba/blogsite.git
